name: Custom Tasks

on:
  workflow_dispatch:

permissions: read-all

jobs:
  enable-logs: # This would be 1 enumeration, after CTS has setup the environment with the correct OS type and version.
    name: Enable Logs
    runs-on:
    - self-hosted
    - "x64"
    - "secnetperf"
    - "windows"
    steps:
    - name: Capture Logs
      shell: pwsh
      run: |
        Write-Host 'Connecting to netperf-peer'
        $Session = New-PSSession -ComputerName "netperf-peer" -ConfigurationName PowerShell.7
        Invoke-Command -Session $Session -ScriptBlock {
            try { logman query profsvc -ets } catch {}
            C:\_work\quic\artifacts\bin\windows\x64_Release_schannel\secnetperf.exe
            try { logman stop profsvc -ets } catch {}
            dir $env:WINDIR\System32\LogFiles\WMI\profsvc*
        }
        Write-Host 'Setting up log folder'
        Remove-Item .\artifacts\logs -Force -Recurse -ErrorAction Continue | Out-Null
        mkdir .\artifacts\logs | Out-Null
        Write-Host 'Copying out log files'
        Copy-Item -FromSession $Session C:\Windows\System32\LogFiles\WMI\profsvc.etl.* .\artifacts\logs
        Write-Host 'Deleting log files from remote'
        Invoke-Command -Session $Session -ScriptBlock {
            del $env:WINDIR\System32\LogFiles\WMI\profsvc*
        }
    - name: Upload Logs
      if: ${{ always() }}
      uses: actions/upload-artifact@v4
      with:
        name: profsvc
        path: artifacts/logs
