name: Custom Tasks

on:
  workflow_dispatch:
    inputs:
      os:
        description: 'Windows OS Version'
        required: false
        default: "2022"
        type: choice
        options:
          - "2025"
          - "2022"
          - "2019"

permissions: write-all

jobs:
  testjob:
    runs-on: ubuntu-latest
    steps:
      - name: Print re-run attempt
        run: echo "Rerun attempt - ${{ github.run_number }}"
        