name: Custom Tasks

on:
  workflow_dispatch:

permissions: read-all

jobs:
  enable-logs: # This would be 1 enumeration, after CTS has setup the environment with the correct OS type and version.
    name: Enable Logs
    runs-on:
    - self-hosted
    - "x64"
    - "secnetperf"
    - "windows"
    steps:
    - name: Capture Logs
      shell: pwsh
      run: |
        Write-Host 'Connecting to netperf-peer'
        $Session = New-PSSession -ComputerName "netperf-peer" -ConfigurationName PowerShell.7
        Invoke-Command -Session $Session -ScriptBlock {
            reg query HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\WMI\Autologger
            reg query HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\WMI\Autologger\profsvc
            try { logman query profsvc } catch {}
            try { logman query profsvc -ets } catch {}
            C:\_work\quic\artifacts\bin\windows\x64_Release_schannel\secnetperf.exe
            try { logman stop profsvc } catch {}
            try { logman stop profsvc -ets } catch {}
            dir $env:WINDIR\System32\LogFiles\WMI\profsvc*
        }
        mkdir .\artifacts\logs | Out-Null
        Copy-Item -FromSession $Session C:\Windows\System32\LogFiles\WMI\profsvc.etl.* .\artifacts\logs
    - name: Upload Logs
      if: ${{ always() }}
      uses: actions/upload-artifact@v4
      with:
        name: profsvc
        path: artifacts/logs
