name: Custom Tasks

on:
  workflow_dispatch:

permissions: read-all

jobs:
  enable-logs: # This would be 1 enumeration, after CTS has setup the environment with the correct OS type and version.
    name: Enable Logs
    runs-on:
    - self-hosted
    - "x64"
    - "secnetperf"
    - "windows"
    steps:
    - name: Checkout repository
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
    - name: Enable Logs
      shell: pwsh
      run: |
        Write-Host 'Connecting to netperf-peer'
        $Session = New-PSSession -ComputerName "netperf-peer" -ConfigurationName PowerShell.7
        if ($null -eq $Session) {
            Write-Host 'Failed to connect'
        }
        Write-Host 'Copy reg to peer'
        Copy-Item -ToSession $Session .\.github\workflows\profsvc.reg -Destination C:\_work\quic\scripts -ErrorAction Continue
        Write-Host 'Enabling logs'
        Invoke-Command -Session $Session -ScriptBlock {
            dir C:\_work\quic\scripts\profsvc.reg
            reg import C:\_work\quic\scripts\profsvc.reg
        } -ErrorAction Continue
        Write-Host 'Restarting netperf-peer'
        Invoke-Command -Session $Session -ScriptBlock {    
            shutdown /r /t 0
        }
        Start-Sleep -Seconds 30
        Write-Host 'Done'

    - name: Capture Logs
      shell: pwsh
      run: |
        Write-Host 'Connecting to netperf-peer'
        $Session = New-PSSession -ComputerName "netperf-peer" -ConfigurationName PowerShell.7
        Invoke-Command -Session $Session -ScriptBlock {
            C:\_work\quic\artifacts\bin\windows\x64_Release_schannel\secnetperf.exe
            logman flush profsvc -ets
            dir %WINDIR%\System32\LogFiles\WMI\profsvc*
        }
