name: QUIC

on:
  workflow_dispatch:
    inputs:
      run_id:
        required: true
        default: ''
        type: string
      ref:
        required: false
        default: ''
        type: string
  repository_dispatch:
    types: [run-quic]
      # Args: { guid, ref, sha, run_id }

concurrency:
  group: quic-${{ github.event.client_payload.sha || inputs.ref }}
  cancel-in-progress: true

permissions: read-all

jobs:
  # For automated identification of the workflow.
  name:
    name: For ${{ github.event.client_payload.guid }}
    needs: []
    runs-on: ubuntu-20.04
    steps:
    - run: echo "no op"

  test:
    name: Test Performance
    strategy:
      fail-fast: false
      matrix:
        vec: [
          { plat: "windows", arch: "x64", os: "windows-2022", tls: "schannel" },
        ]
    runs-on:
    - self-hosted
    - "${{ matrix.vec.plat }}"
    - "${{ matrix.vec.arch }}"
    - "azure"
    steps:
    - name: Checkout MsQuic
      uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac
      with:
        repository: microsoft/msquic
        ref: ${{ github.event.client_payload.sha || github.event.client_payload.ref || inputs.ref || 'main' }}
    - name: Download MsQuic Artifacts
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        run_id: ${{ github.event.client_payload.run_id }}
        name: Release-${{ matrix.vec.plat }}-${{ matrix.vec.os }}-${{ matrix.vec.arch }}-${{ matrix.vec.tls }}
        path: artifacts
    - name: Run secnetperf
      shell: pwsh
      run: scripts/secnetperf.ps1
