name: QUIC
on:
  repository_dispatch:
    types: [run-quic]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout MsQuic
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac
        with:
          ref: ${{ github.event.client_payload.ref }}
          repository: microsoft/msquic
          path: './msquic'
      - name: Prepare Machine
        shell: pwsh
        run: msquic/scripts/prepare-machine.ps1 -ForBuild
      - name: Build For Test
        shell: pwsh
        run: msquic/scripts/build.ps1 -Config Release -DisableTest
