name: QUIC

on:
  workflow_dispatch:
    inputs:
      ref:
        required: false
        default: ''
        type: string
  repository_dispatch:
    types: [run-quic]

permissions: read-all

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout NetPerf
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac
      - name: Checkout MsQuic
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac
        with:
          ref: ${{ inputs.ref || github.event.client_payload.ref }}
          repository: microsoft/msquic
          path: './msquic'
      - shell: pwsh
        run: dir msquic
      - name: Build
        uses: ./msquic/.github/workflows/build-reuse-unix.yml
