name: QUIC

on:
  push:
    branches:
    - main
  workflow_dispatch:
    inputs:
      ref:
        required: false
        default: ''
        type: string
  repository_dispatch:
    types: [run-quic]

permissions: read-all

jobs:
  build-windows:
    name: WinUser
    needs: []
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-2022']
        arch: [x64]
        tls: [schannel, openssl, openssl3]
        xdp: ['', '-UseXdp']
    uses: microsoft/msquic/.github/workflows/build-reuse-win.yml@nibanks/specify-checkout-repo
    with:
      os: ${{ matrix.os }}
      arch: ${{ matrix.arch }}
      tls: ${{ matrix.tls }}
      xdp: ${{ matrix.xdp }}
      # ref: ${{ github.event.client_payload.ref || inputs.ref || 'main' }}

  build-windows-kernel:
    name: WinKernel
    needs: []
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-2022']
        arch: [x64]
        tls: [schannel]
    uses: microsoft/msquic/.github/workflows/build-reuse-winkernel.yml@nibanks/specify-checkout-repo
    with:
      os: ${{ matrix.os }}
      arch: ${{ matrix.arch }}
      tls: ${{ matrix.tls }}
      # ref: ${{ github.event.client_payload.ref || inputs.ref || 'main' }}

  build-ubuntu:
    name: Ubuntu
    needs: []
    strategy:
      fail-fast: false
      matrix:
        plat: [linux]
        os: ['ubuntu-20.04']
        arch: [x64]
        tls: [openssl, openssl3]
    uses: microsoft/msquic/.github/workflows/build-reuse-unix.yml@nibanks/specify-checkout-repo
    with:
      plat: ${{ matrix.plat }}
      os: ${{ matrix.os }}
      arch: ${{ matrix.arch }}
      tls: ${{ matrix.tls }}
      # ref: ${{ github.event.client_payload.ref || inputs.ref || 'main' }}
