name: QUIC

on:
  workflow_dispatch:
    inputs:
      logprofile:
        required: false
        default: ''
        type: string
      ref:
        required: false
        default: ''
        type: string
  repository_dispatch:
    types: [run-quic]
      # Args: { guid, sha, ref, pr }

concurrency:
  group: quic-${{ github.event.client_payload.pr || github.event.client_payload.sha }}
  cancel-in-progress: true

permissions: read-all

jobs:
  # For automated identification of the workflow.
  name:
    name: For ${{ github.event.client_payload.guid }}
    needs: []
    runs-on: ubuntu-20.04
    steps:
    - run: echo "no op"

  build-windows:
    name: Build WinUser
    needs: []
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-2022']
        tls: [schannel] # , openssl, openssl3]
    uses: microsoft/msquic/.github/workflows/build-reuse-win.yml@main
    with:
      os: ${{ matrix.os }}
      tls: ${{ matrix.tls }}
      ref: ${{ github.event.client_payload.sha || github.event.client_payload.ref || inputs.ref || 'main' }}

  build-windows-kernel:
    name: Build WinKernel
    needs: []
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-2022']
    uses: microsoft/msquic/.github/workflows/build-reuse-winkernel.yml@main
    with:
      os: ${{ matrix.os }}
      ref: ${{ github.event.client_payload.sha || github.event.client_payload.ref || inputs.ref || 'main' }}

  build-ubuntu:
    name: Build Ubuntu
    needs: []
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-20.04']
        tls: [openssl, openssl3]
    uses: microsoft/msquic/.github/workflows/build-reuse-unix.yml@main
    with:
      os: ${{ matrix.os }}
      tls: ${{ matrix.tls }}
      ref: ${{ github.event.client_payload.sha || github.event.client_payload.ref || inputs.ref || 'main' }}

  test-windows:
    name: Test Windows
    needs: [build-windows]
    strategy:
      fail-fast: false
      matrix:
        vec: [
          { plat: "windows", os: "windows-2022", arch: "x64", tls: "schannel" },
        ]
    runs-on:
    - self-hosted
    - ${{ matrix.vec.plat }}
    - ${{ matrix.vec.arch }}
    - "secnetperf"
    steps:
    - name: Checkout repository
      uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac
      with:
        repository: microsoft/msquic
        ref: ${{ github.event.client_payload.sha || github.event.client_payload.ref || inputs.ref || 'main' }}
    - uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a
      with:
        name: Release-${{ matrix.vec.plat }}-${{ matrix.vec.os }}-${{ matrix.vec.arch }}-${{ matrix.vec.tls }}
        path: artifacts
    - name: Run secnetperf
      shell: pwsh
      run: scripts/secnetperf.ps1 -LogProfile ${{ github.event.client_payload.logprofile || inputs.logprofile || 'NULL' }}
    - name: Upload Test Results
      if: ${{ always() }}
      uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32
      with:
        name: test-results-${{ matrix.vec.plat }}-${{ matrix.vec.os }}-${{ matrix.vec.arch }}-${{ matrix.vec.tls }}
        path: test_result.json
    - name: Upload Logs
      if: ${{ always() }}
      uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32
      with:
        name: logs_Release_${{ matrix.vec.plat }}_${{ matrix.vec.arch }}
        path: artifacts/logs

  save-test-results-windows: # NOTE: We can tweak this job to change the way we save perf data (orphan branch vs. database solution)
    name: Save test results windows
    needs: [test-windows]
    strategy:
      fail-fast: false
      matrix:
        vec: [
          { plat: "windows", os: "windows-2022", arch: "x64", tls: "schannel" },
        ]
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac
      with:
        repository: microsoft/netperf
        ref: deploy
    - uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a
      with:
        name: test-results-${{ matrix.vec.plat }}-${{ matrix.vec.os }}-${{ matrix.vec.arch }}-${{ matrix.vec.tls }}
        path: test_result.json
    - name: Commit test results
      run: |
          mv test_result.json data/secnetperf/${{ github.event.client_payload.sha || github.event.client_payload.ref || inputs.ref || 'main' }}.json
          git config user.email "quicdev@microsoft.com"
          git config user.name "QUIC Dev[bot]"
          git add data
          git commit -m "Add test results for ${{ github.event.client_payload.sha || github.event.client_payload.ref || inputs.ref || 'main' }}"
          git push
