name: QUIC

on:
  workflow_dispatch:
    inputs:
      ref:
        required: false
        default: ''
        type: string
  repository_dispatch:
    types: [run-quic]
      # Args: { guid, ref, sha, run_id }

concurrency:
  group: quic-${{ github.event.client_payload.sha || inputs.ref }}
  cancel-in-progress: true

permissions: read-all

jobs:
  # For automated identification of the workflow.
  name:
    name: For ${{ github.event.client_payload.guid }}
    needs: []
    runs-on: ubuntu-20.04
    steps:
    - run: echo "no op"

  test-windows:
    name: Test Windows
    needs: [build-windows]
    strategy:
      fail-fast: false
      matrix:
        vec: [
          { config: "Release", plat: "windows", os: "windows-2022", arch: "x64", tls: "schannel" },
        ]
    runs-on:
    - self-hosted
    - "Windows"
    - "azure"
    - "X64"
    steps:
    - name: Checkout MsQuic
      uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac
      with:
        repository: microsoft/msquic
        ref: ${{ github.event.client_payload.sha || github.event.client_payload.ref || inputs.ref || 'main' }}
    - name: Download MsQuic Artifacts
      env:
          GH_TOKEN: ${{ github.token }}
      run: |
        New-Item -Path artifacts -ItemType Directory -Force -ErrorAction SilentlyContinue
        $ArtifactName = "${{ matrix.vec.config }}-${{ matrix.vec.plat }}-${{ matrix.vec.os }}-${{ matrix.vec.arch }}-${{ matrix.vec.tls }}${{ matrix.vec.xdp }}"
        gh run download ${{ github.event.client_payload.run_id }} -R microsoft/msquic -n $ArtifactName -D artifacts
    - name: Run secnetperf
      shell: pwsh
      run: scripts/secnetperf.ps1
