name: QUIC

on:
  push:
    branches:
    - main
  workflow_dispatch:
    inputs:
      ref:
        required: false
        default: ''
        type: string
  repository_dispatch:
    types: [run-quic]

permissions: read-all

jobs:
  Build:
    uses: microsoft/msquic/.github/workflows/build-reuse-unix.yml@nibanks/specify-checkout-repo # ${{ github.event.client_payload.ref || inputs.ref || 'main' }}
